const mockDataAccount = [
    {
        no: 1,
        username: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
        nama: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
        nip: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
        jabatan: `100%`,
        instansi: `3`,
        tanggal: false,
        status: true,
    },
    {
        no: 2,
        username: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
        nama: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
        nip: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
        jabatan: `100%`,
        instansi: `3`,
        tanggal: true,
        status: false,
    },
    {
        no: 3,
        username: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
        nama: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
        nip: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
        jabatan: `100%`,
        instansi: `3`,
        tanggal: false,
        status: true,
    },
    {
        no: 4,
        username: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
        nama: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
        nip: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
        jabatan: `100%`,
        instansi: `3`,
        tanggal: true,
        status: false,
    },
    {
        no: 5,
        username: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
        nama: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
        nip: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
        jabatan: `100%`,
        instansi: `3`,
        tanggal: false,
        status: true,
    },
    {
        no: 6,
        username: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
        nama: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
        nip: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
        jabatan: `100%`,
        instansi: `3`,
        tanggal: true,
        status: true,
    },
    {
        no: 7,
        username: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
        nama: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
        nip: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
        jabatan: `100%`,
        instansi: `3`,
        tanggal: false,
        status: false,
    },
]

export default mockDataAccount;
