const mockDataReport = [
  {
      no: 1,
      agency_name: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
      work_unit: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
      information: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
      registration_progress: `100%`,
      regis_number: `3`,
      published: false,
  },
  {
      no: 2,
      agency_name: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
      work_unit: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
      information: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
      registration_progress: `100%`,
      regis_number: `3`,
      published: true,
  },
  {
      no: 3,
      agency_name: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
      work_unit: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
      information: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
      registration_progress: `100%`,
      regis_number: `3`,
      published: false,
  },
  {
      no: 4,
      agency_name: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
      work_unit: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
      information: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
      registration_progress: `100%`,
      regis_number: `3`,
      published: true,
  },
  {
      no: 5,
      agency_name: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
      work_unit: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
      information: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
      registration_progress: `100%`,
      regis_number: `3`,
      published: false,
  },
  {
      no: 6,
      agency_name: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
      work_unit: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
      information: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
      registration_progress: `100%`,
      regis_number: `3`,
      published: true,
  },
  {
      no: 7,
      agency_name: `Kementerian Komunikasi dan Informatika / retno dewiyanti / 198301282008032001`,
      work_unit: `Pendaftaran Penyelenggara Sistem Elektronik / Direktorat TATA KELOLA APLIKASI INFORMATIKA`,
      information: `Pendukung Layanan Sistem Elektronik layanan publik non instansi penyelenggara negara`,
      registration_progress: `100%`,
      regis_number: `3`,
      published: false,
  },
]

export default mockDataReport;